
package de.sternico.bpm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BpmEngineAccessor", targetNamespace = "http://service.bpm.sternico.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BpmEngineAccessor {


    /**
     * 
     * @return
     *     returns de.sternico.bpm.service.TaskDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public TaskDTOArray queryAllTasks();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void startProcessInstanceByKey(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void correlateMessage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void finishTask(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        HashMapContainer arg1);

    /**
     * 
     */
    @WebMethod
    public void debugProcessDefinitionKeys();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void correlateMessageWithBusinessKey(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
