
package de.sternico.bpm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BpmEngineAccessor", targetNamespace = "http://service.bpm.sternico.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BpmEngineAccessor {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void startProcessInstanceByKey(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    public void correlateMessage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     */
    @WebMethod
    public void debugProcessDefinitionKeys();

}
